export const defaultAppSettings: AppSettings = {
  fontFamily: "system-ui",
  borderRadius: 8,
  primaryColor: "#1ed760",
  backgroundColor: "",
  audioQuality: "auto",
  followSystemVolume: true,
  hiddenMenuKeys: [],
  displayMode: "list",
  themeMode: "system",
  pageTransition: "none",
  showSearchHistory: true,
  reportPlayHistory: true,
  sponsorBlockEnabled: false,
};
